version: '3.6'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - product_network

  # #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webservers
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    # env_file:
    #   - ./.env
    ports:
      - "8001:80"
      - "44333:443"
    networks:
      - product_network

  #MySQL Service
  db:
    image: mysql:8.0.29
    container_name: product_db
    restart: unless-stopped
    tty: true
    ports:
      - "33065:3306"
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    networks:
      - product_network

    volumes:
      - mysqldata:/var/lib/mysql

#Docker Networks
networks:
  product_network:
    driver: bridge
    

volumes:
  mysqldata: